### ISSUE TITLE
fs.exists deprecated

### ISSUE THREAD

**Issue by FNCxPro** [oskikiboy/Tensa#1]
`fs.exists` is deprecated as of v1.0.0 of node.js, https://nodejs.org/api/fs.html#fs_fs_exists_path_callback  
https://github.com/oskikiboy/Tensa/blob/master/src/bot/internals/fileExists.js#L6

**Comment by oskikiboy** [comment]
Will fix

**Comment by oskikiboy** [comment]
Fixed in commit https://github.com/oskikiboy/Tensa/commit/3943ad215df7844c97e025bcbbf8d58654965a84

**Comment by FNCxPro** [comment]
you can add "Closes #1" to the commit description and it automatically closes iirc
